




.build/uno/src/towerlight.cpp : src/towerlight.ino
	@mkdir -p .build/uno/src
	@echo [93msrc/towerlight.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/uno/src/towerlight.cpp
	@true

