




.build/nano328/src/rgb_serial.cpp : src/rgb_serial.ino
	@mkdir -p .build/nano328/src
	@echo [93msrc/rgb_serial.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/nano328/src/rgb_serial.cpp
	@true

